### ISSUE TITLE
Investigate dataloading and data-caching performance

### ISSUE THREAD

**Issue by callumm-graphcore** [datamol-io/graphium#189]
Writing this task more as a quick reminder to myself so I don't come back on Monday having forgotten that I need to look at this stuff

- [x] Measure throughput of dataloading with PCQM4Mv2
- [x] Investigate alternate methods of caching
- [ ] Investigate usage of tools such as PyArrow
- [x] Investigate splitting the dataloader so each worker owns a piece of the dataset rather than the whole thing

**Comment by DomInvivo** [comment]
Many improvements in the Dataloader in PR #312
