### ISSUE TITLE
GPS++ config should produce correct base shapes for muP

### ISSUE THREAD

**Issue by callumm-graphcore** [datamol-io/graphium#220]
- [x] Fix #206
- [x] Task heads should have fixed output dimension (they currently don't)
- [ ] Check that positional encoders have correct dimensions
- [ ] Check `pre_nn` and `pre_nn_edges`
- [ ] Check `post_nn` and `post_nn_edges`

**Comment by DomInvivo** [comment]
@callumm-graphcore , I think this was fixed right? If not, feel free to re-open the issue.
