### ISSUE TITLE
stochastic depth (drop path, graph dropout) on edges

### ISSUE THREAD

**Issue by zhiyil-graphcore** [datamol-io/graphium#229]
It's actually achievable after a second thought:
1, generate mask for graphs using Bernoulli distribution (same as what we are doing now):
`graph_mask = [0, 1, ,1, 1, 0, 0]` # if on IPU last graph must be 0 as it is a fake padded graph 
2, get `node_graph_idx` by `batch.batch` (same as what we are doing now)
`batch.batch example: [0, 0, 0, 1, 1, 2, 2, 2, 2, 3, 3]`
3, use gather to get `edge_graph_idx`:
`edge_graph_idx = batch.batch[sender]`
sender would be like: `[0, 2, 1, / 4,/ 5, 5,  6, 7, 8, ,8,/ 9, 9]` equal to number of edges
`edge_graph_idx  [0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 3, 3]`
3, use gather to get graph dropout mask for edges:
`edge_mask= graph_mask[edge_graph_idx]`

**Comment by DomInvivo** [comment]
Closing this issue since it's not a priority
