### ISSUE TITLE
Investigate issue when using np.float16 as label dtype gives error 

### ISSUE THREAD

**Issue by zhiyil1230** [datamol-io/graphium#249]
error message 
`Traceback (most recent call last): File "expts/main_run_multitask.py", line 94, in <module> main(cfg) File "expts/main_run_multitask.py", line 67, in main datamodule.prepare_data() File "/nethome/zhiyil/git/goli/goli/data/datamodule.py", line 964, in prepare_data task_df[task] = self._read_csv(args.df_path, usecols=usecols, dtype=label_dtype) File "/nethome/zhiyil/git/goli/goli/data/datamodule.py", line 538, in _read_csv df = pd.read_csv(path, **kwargs) File "/nethome/zhiyil/.venv/goli_ipu/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 918, in read_csv return _read(filepath_or_buffer, kwds) File "/nethome/zhiyil/.venv/goli_ipu/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 589, in _read return parser.read(nrows) File "/nethome/zhiyil/.venv/goli_ipu/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1721, in read ) = self._engine.read(  # type: ignore[attr-defined] File "/nethome/zhiyil/.venv/goli_ipu/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 231, in read chunks = self._reader.read_low_memory(nrows) File "pandas/_libs/parsers.pyx", line 815, in pandas._libs.parsers.TextReader.read_low_memory File "pandas/_libs/parsers.pyx", line 892, in pandas._libs.parsers.TextReader._read_rows File "pandas/_libs/parsers.pyx", line 1055, in pandas._libs.parsers.TextReader._convert_column_data File "pandas/_libs/parsers.pyx", line 1417, in pandas._libs.parsers._maybe_upcast KeyError: dtype('float16')`

**Comment by DomInvivo** [comment]
@zhiyil-graphcore was this issue fixed?
