### ISSUE TITLE
Potential `ZeroDivisionError`/other weird behaviour in packing

### ISSUE THREAD

**Issue by callumm-graphcore** [datamol-io/graphium#294]
If `big + small == batch_size` in `hybrid_packing()` then in this line:
```
    medium_packs = fast_packing(num_nodes[medium_graphs], batch_size=batch_size - big - small)
```

The value of the `batch_size` parameter is `0`, which leads to a `ZeroDivisionError` here in `fast_packing`:

```
    ipu_batch_size = int(len(num_nodes) / batch_size)
```

I think that the `batch_size` parameter here could end up being negative, too, which would also cause undesirable behaviour (haven't really investigated this).

**Comment by DomInvivo** [comment]
Fixed somewhere
