### ISSUE TITLE
Cache features rather than datasets/datamodules

### ISSUE THREAD

**Issue by callumm-graphcore** [datamol-io/graphium#312]
I would like to implement a "feature cache", which is a mapping from molecules to features stored on disk as follows:
```
.goli_feature_cache
|_ <mol1>
|___ <feat1>
|___ <feat2>
|___ <feat3>
|_ <mol2>
|___ <feat1>
|___ <feat2>
|___ <feat3>
```

At the moment, we cache data according to the full dataset configuration, and even a small change invalidates the entire cache. With this, users could add new features to their configs, tweak the sample size, and change the splits without having to run all of the featurization again. Users sharing a common workspace could even share such a cache, though this could present some difficulties.

We would still need to store a mapping from indices to molecules for each datamodule config so that features can be loaded from the right index.

There are some open questions about how to implement this:
- How do we make it so each featurizer knows that the cache is there?
- How do we implement this in the datamodule/dataset classes?
- Is checking for the existence of a cached feature much faster than just doing the featurization?

**Comment by DomInvivo** [comment]
Done in some PR
