### ISSUE TITLE
Make sure all configs on the main branch are compatible with experimental changes (i.e. seed -> checkpoint name)

### ISSUE THREAD

**Issue by s-maddrellmander** [datamol-io/graphium#354]
Making a note of this here to make sure it's not lost prior to publicising the library

**Comment by DomInvivo** [comment]
@s-maddrellmander don't forget to close this issue when done

**Comment by DomInvivo** [comment]
The new configs in #421 and #423 are modular and much more maintainable. The issue mentioned here is fixed.
