### ISSUE TITLE
Improve speed + memory issues due to dataloading in multi-task

### ISSUE THREAD

**Issue by DomInvivo** [datamol-io/graphium#356]
Current dataloading saves all processed molecules to a different pickle file, and reads each one at loading time. Despite this being better than putting everything on the RAM, it still has issues that appear when using very large datasets with thousands of labels.

Perhaps there's a better way of doing this by loading data from HDF5 or parquet files?

The dataset loading is done here:
https://github.com/datamol-io/graphium/blob/2790af4d95e8924671cc666fac002fd003130618/graphium/data/dataset.py#L358

The dataset saving is done here:
https://github.com/datamol-io/graphium/blob/2790af4d95e8924671cc666fac002fd003130618/graphium/data/datamodule.py#L1257

**Comment by zhiyil-graphcore** [comment]
@joao-alex-cunha has found that if we don't save the preds and targets for each step, the RAM goes back to be similar like the PCQ4M. The new lightning version might help with this.
![Screenshot 2023-06-16 at 15 48 10](https://github.com/datamol-io/graphium/assets/86362692/c1660e69-ef80-4570-be28-44743417ace2)

**Comment by DomInvivo** [comment]
But we need to return the preds and targets to accurately compute the Loss and Metrics in `on_train_batch_end` over the accumulation of batches.

Ideally, we would not need to do that and use [torchmetrics update function](https://torchmetrics.readthedocs.io/en/stable/pages/implement.html#torchmetrics.Metric.update), but the problem is that all metrics in `torchmetrics` don't work with NaNs, so we must use the `MetricWrapper` or re-implement each one of them to support NaNs in the labels directly on the `torchmetrics` repo. That would be the best solution, but very time-consuming.

@joao-alex-cunha  Any thoughts on how to return something in `training_step` while still deleting the returned objects once we finish the `on_train_batch_end` step? Right now, the config doesn't use any metric on the training, but it shouldn't be the only possible behaviour.

**Comment by DomInvivo** [comment]
This was fixed by using lightning>=2.0, which avoids returning the train and preds at `on_train_batch_end`
