### ISSUE TITLE
Hydrogen in dataset error

### ISSUE THREAD

**Issue by zhiyil-graphcore** [datamol-io/graphium#360]
When removing hydrogen, some molecules end up empty. in `datamodule.py `
`df = df[df[df.columns[0]].apply(lambda x: has_atoms_after_h_removal(x))]` was used temporarily, but this does not work for the test and PCQM4M dataset. need a proper fix.

**Comment by DomInvivo** [comment]
In the `prepare_data` method, we filter the molecules that failed featurization here:
https://github.com/datamol-io/graphium/blob/ffe3ce6320ceab1ebc6a5cdee8cba2e2f9eadce5/graphium/data/datamodule.py#L1061

However, some molecules can succeed featurization, but when you then need to make sure that the number of nodes/edges in the graph match the number of nodes/edges expected in the labels, if not filter them out.

- Loop through all the molecules
  - Loop through all the labels that start with `node_`, `edge_` and `nodepair_` to get the expected number of nodes and edges
  - Ignore all the `NaN`s or `None`s in these label columns.
  - Loop through all the `features` which are supposed to be either a `GraphDict` or `pyg.data.Data`. And get the number of nodes and edges with the properties `.num_nodes` and `.num_edges`.
  - Make sure that all number of nodes and number of edges are consistent. 
  - Every time that you find an inconsistency, replace the given element in `features` by a string explaining the error `f"Inconsistent number of nodes found for '{this_smiles}': {set(all_num_nodes)}"
