### ISSUE TITLE
Failing unit tests cuz OGB has changed its URL for freesolv

### ISSUE THREAD

**Issue by hadim** [datamol-io/graphium#365]
See the CI logs: https://github.com/datamol-io/graphium/actions/runs/5373722733/jobs/9748378988

```
FAILED tests/test_datamodule.py::Test_DataModule::test_caching - ValueError: The file being copied does not exist: http://snap.stanford.edu/ogb/data/graphproppred/csv_mol_download/freesolv.zip
FAILED tests/test_datamodule.py::Test_DataModule::test_ogb_datamodule - ValueError: The file being copied does not exist: http://snap.stanford.edu/ogb/data/graphproppred/csv_mol_download/freesolv.zip
```

**Comment by hadim** [comment]
ping @DomInvivo

**Comment by DomInvivo** [comment]
The Stanford servers are down
https://cs.stanford.edu/srcf_404/

Let's ignore that for now and circle back in a few days.

![image](https://github.com/datamol-io/graphium/assets/47570400/29fa0cf4-6d5b-4f88-8eff-f059096092ba)

**Comment by DomInvivo** [comment]
The URL is now working
