### ISSUE TITLE
Entity name hardcoded for wandb

### ISSUE THREAD

**Issue by michalkoziarski** [datamol-io/graphium#366]
The name of entity is hardcoded in https://github.com/datamol-io/graphium/blob/256635568aaa45dae3da87efab4e1b0e363308ec/expts/main_run_multitask.py#L57 to `"multitask-gnn"`, so people without access get
```
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
```
when trying to run experiments.

The easiest option would be to just remove it, but I am not sure if that won't break workflow for people currently running experiments (when they start getting logged to different project).

**Comment by DomInvivo** [comment]
Fixed in PR #421 and #423 , where `entity` is passed in the hydra-configs, see example here: https://github.com/datamol-io/graphium/blob/f96c1b60b4d86e2fde0f3660b2916c14de388749/expts/neurips2023_configs/base_config/small.yaml#L6
