### ISSUE TITLE
installing lightning dependency not working correctly 

### ISSUE THREAD

**Issue by shenyangHuang** [datamol-io/graphium#368]
currently when installing the IPU dependencies, the following command will throw an error:
`PACKAGE_NAME=pytorch pip install -r requirements_ipu.txt`
error message
`ERROR: Could not find a version that satisfies the requirement lightning (unavailable) (from versions: 1.8.0rc1, 1.8.0rc2, 1.8.0, 1.8.0.post1, 1.8.1, 1.8.2, 1.8.3, 1.8.3.post0, 1.8.3.post1, 1.8.3.post2, 1.8.4, 1.8.4.post0, 1.8.5, 1.8.5.post0, 1.8.6, 1.9.0rc0, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 2.0.0rc0, 2.0.0, 2.0.1, 2.0.1.post0, 2.0.2, 2.0.3, 2.0.4, 2022.6.15, 2022.6.15.post1, 2022.6.15.post2, 2022.7.18, 2022.8.2, 2022.8.9, 2022.8.17, 2022.9.8, 2022.9.22, 2022.10.7, 2022.10.20, 2022.10.25)`

This is likely caused by lightning version problem in the `requirements_ipu.txt` which shows the following
```
lightning @ git+https://github.com/Lightning-AI/lightning@ca30fd7752582201a3966806c92e3acbbaf2a045
lightning-graphcore @ git+https://github.com/Lightning-AI/lightning-Graphcore
```

we should use a different version of lightning or find other ways to fix this issue

**Comment by callumm-graphcore** [comment]
I think `PACKAGE_NAME=pytorch` might no longer be necessary?

**Comment by joao-alex-cunha** [comment]
Hi Andy, I’m on holiday won’t be back for another week and a half. I did not see those issues. If you can share how you are creating the environment and installing the library, I might be able to provide some limited help until I'm back

**Comment by shenyangHuang** [comment]
I am tackling this issue in PR #370 , will investigate more as well
