### ISSUE TITLE
expts/config/config_gps_10M_pcqm4m.yaml `num_heads` not defined

### ISSUE THREAD

**Issue by joao-alex-cunha** [datamol-io/graphium#401]
While trying to test a GPS model, I tried to run this config and it an issue where num_heads is not defined in the config as it is attempting to read the value from an alias that doesn't exist anymore. Previously the value was 2.

To reproduce:
python3 expts/main_run_multitask.py --config expts/configs/config_gps_10M_pcqm4m.yaml

**Comment by DomInvivo** [comment]
`num_heads` is now defined here, after refactoring the configs: https://github.com/datamol-io/graphium/blob/f96c1b60b4d86e2fde0f3660b2916c14de388749/expts/hydra-configs/model/gpspp.yaml#L20C22-L20C22
