### ISSUE TITLE
The config override doesn't work for deleting keys (and I didn't find a straightforward fix).

### ISSUE THREAD

**Issue by DomInvivo** [datamol-io/graphium#404]
The config override doesn't work for deleting keys (and I didn't find a straightforward fix). `loss_scaling` seems to be a argument specific to Graphcore optimizers

_Originally posted by @luis-mueller in https://github.com/datamol-io/graphium/pull/378#discussion_r1263960268_
            
Updating keys is a good default behaviour, but sometimes we want to destroy something from the base config, like removing the `loss_scaling` or if the base config has edge features, and we don't want them in our modified config.

Perhaps the solution is simply to create a simpler version of the base config? For example one that wouldn't have the accelerator?

**Comment by cwognum** [comment]
The [`hydra` overwrite syntax](https://hydra.cc/docs/advanced/override_grammar/basic/) comes to mind (`hydra` is based on `omegaconf`). It's CLI based and among other things, they support the removal of a key (e.g. `foo.bar`) from a config through the `~` prefix (e.g. `/path/to/app.py ~foo.bar`).

**Comment by luis-mueller** [comment]
I have some experience using hydra and think it could be an option. There one has more flexiblity when composing configs. However, it would require some changes to the current config format. Another benefit of hydra is that we’d be building on existing open-source and best practices for config handling and don’t have to maintain our own solution.

**Comment by cwognum** [comment]
Using hydra, it's also nice to be able to split each config in components that can be reused. There seems to be a lot of "~code~ config repetition" right now.

**Comment by luis-mueller** [comment]
@cwognum @DomInvivo I created a PR where I am demonstrating how our configs could look with hydra.
