### ISSUE TITLE
Issues for loading from RAM instead of from Disk

### ISSUE THREAD

**Issue by DomInvivo** [datamol-io/graphium#431]
- [x] The `DatasetSubsampler` class fails if `processed_graph_data_path` is None, due to this line: https://github.com/datamol-io/graphium/blob/10fe04b2a7983523d9829ac37c4bfa3d8f7391c8/graphium/data/sampler.py#L28

- [x] `cache_data_path` should be depreciated in favor of `processed_graph_data_path`: https://github.com/datamol-io/graphium/blob/10fe04b2a7983523d9829ac37c4bfa3d8f7391c8/graphium/data/datamodule.py#L773

- [x] `load_from_file` should be its own parameter. Depending on `processed_graph_data_path` means that either:
  - We can cache the data and dataloading from disk
  - We cannot cache and we can do dataloading from RAM
  - We need the option of caching while doing dataloading from RAM, and this will be enabled by a new `load_from_file` parameter in the Datamodule

- [x] Why is `normalize_label` only applied when dataloading is from RAM? Where is it applied on disk? https://github.com/datamol-io/graphium/blob/10fe04b2a7983523d9829ac37c4bfa3d8f7391c8/graphium/data/datamodule.py#L1300

**Comment by WenkelF** [comment]
> Why is `normalize_label` only applied when dataloading is from RAM? Where is it applied on disk?

This is fine because `_save_data_to_files()` internally calls `_make_multitask_dataset(..., load_from_file=False)`, i.e., label normalization is already applied to datasets loaded from disk.
