### ISSUE TITLE
Run more ToyMix baselines

### ISSUE THREAD

**Issue by DomInvivo** [datamol-io/graphium#459]
Run the ToyMix baselines with 150k parameters using the following models:

- [x] GatedGCN
- [x] MPNN+ [sum] (with the `MPNNPlusPyg` class)
- [ ] PNA+ [mean, sum, max] (with the `MPNNPlusPyg` class)
- [ ] Transformer
- [ ] **OPTIONAL** :Transformer with RW-bias, as done in [the GRIT paper](https://arxiv.org/pdf/2305.17589.pdf)
  - Use the full RW matrix by setting the `pos_level` to `nodepair` [here](https://github.com/datamol-io/graphium/blob/6eb79062cbd95a46ac4106f1e83c2dafcb906846/expts/neurips2023_configs/base_config/large.yaml#L167-L168)
  - @WenkelF, can you confirm that the `nodepair` encoding returns the full RW matrix?
  - Change the `output_keys` to `"rw_bias"` [here](https://github.com/datamol-io/graphium/blob/6eb79062cbd95a46ac4106f1e83c2dafcb906846/expts/neurips2023_configs/base_config/large.yaml#L209-L212)
  - Change the `biased_attention_key` to `"rw_bias"` [here](https://github.com/datamol-io/graphium/blob/6eb79062cbd95a46ac4106f1e83c2dafcb906846/expts/hydra-configs/model/gpspp.yaml#L39)
  -  Change the `pos_type` to `rw_transition_probs` [here](https://github.com/datamol-io/graphium/blob/baselines/expts/neurips2023_configs/base_config/large.yaml#L167-L169)

Do the search over:
- Depth 4, 6, 8 (while keeping param count constant)
- LR
- BatchNorm vs LayerNorm

**Comment by WenkelF** [comment]
> @WenkelF, can you confirm that the nodepair encoding returns the full RW matrix?

@DomInvivo it does if `pos_type="rw_transition_probs"` and `pos_level="nodepair"`. If however set to `"rw_return_probs"`, it only returns the diagonal, which is a node-level PE. It would be transferred to nodepair-level using `nodepair_pe = np.concatenate((pe_sum, pe_abs_diff), axis=-1)` for each individual nodepair.

**Comment by WenkelF** [comment]
> PNA [sum]
> PNA [mean, sum, max]

@DomInvivo should we use MPNNPlus instead of PNA here to be consistent with `LargeMix` baselines?

**Comment by DomInvivo** [comment]
Yeah, we could use `MPNNPlusPyg` but be careful about the `mlp_expansion_ratio` that will eat up so many parameters if >1.

**Comment by DomInvivo** [comment]
I rectified what I mean here. Let's call them `MPNN+` and `PNA+` but use the `MPNNPlusPyg` class.

Let's also be careful about the `mlp_expansion_ratio` and `num_node_mlp` that will eat up so many parameters

**Comment by DomInvivo** [comment]
> > @WenkelF, can you confirm that the nodepair encoding returns the full RW matrix?
> 
> @DomInvivo it does if `pos_type="rw_transition_probs"` and `pos_level="nodepair"`. 

Thanks, I updated the instructions.

@WenkelF , can you please provide the configs you'll be using for LargeMix to @engmubarak48 , and the code to estimate param counts, and he shall modify them for ToyMix?

**Comment by engmubarak48** [comment]
@DomInvivo After experimenting with the configurations, I managed to reach 151k with a depth of 4. Sweeping over ```architecture.gnn.depth: [4, 6, 8]``` automatically won't keep parameters constant. How do you suggest maintaining the 150k params with a single-run search via optuna? I'd personally recommend separate sweeps for each depth or limiting the depth range. 

@WenkelF do you happen to search over depth while keeping parameters fixed without doing it manually via sweep?

**Comment by DomInvivo** [comment]
@engmubarak48 we do separate sweeps for the different width/depth ratio.

**Comment by engmubarak48** [comment]
@DomInvivo that makes sense, thanks

**Comment by DomInvivo** [comment]
Closing, as this can be done on a per-project basis, and is not part of Graphium
