### ISSUE TITLE
invalid version when installing in dev mode

### ISSUE THREAD

**Issue by fpour** [datamol-io/graphium#492]
Trying to install Graphium in dev mode by running `pip install --no-deps -e .`, I faced with the following error:
```python
File ".../lib/python3.11/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'dev'
``` 
which results in:
```
Getting requirements to build editable did not run successfully.
  exit code: 1
``` 

The issue can be resolved by replacing the `"dev"` to `2.4.dev1` in the `pyproject.toml` and the `_version.py` (not sure if that second one was needed).

**Comment by DomInvivo** [comment]
@jstlaurent Can you look into this? What's the best way of replacing `"dev"`?

**Comment by jstlaurent** [comment]
@fpour: Can you give more info about your environment? Are you using pyenv, venv, Conda, or something else?

I tried the command in a clean new venv and It worked for me, so I'm trying to see what I'm missing to reproduce the issue.

**Comment by fpour** [comment]
I used `mamba` and just followed the readme procedures. Basically, just ran the following commands:
```shell
mamba env create -f env.yml -n graphium
mamba activate graphium
pip install --no-deps -e .
```

**Comment by jstlaurent** [comment]
That's weird. I tried exactly the same series of instructions and it works fine. Maybe if you reset your conda environment?

```shell
mamba deactivate
mamba env remove -n graphium
```

**Comment by fpour** [comment]
I started a fresh env and don't see the issue anymore.

**Comment by DomInvivo** [comment]
Resolved
