### ISSUE TITLE
Multi-GPU starts W&B more than once

### ISSUE THREAD

**Issue by blazejba** [datamol-io/graphium#493]
In the script `train_finetune_test.py`, branching is in place to start W&B only in the instance of `rank = 0`.  The script looks for an environmental variable called `RANK` that it expects to be set by PTL while launching the same script in a distributed way.

I checked both 1.4.9 and 2.1.2 versions of PTL and in both cases, there is a node rank, which corresponds to a server node, and a local rank which corresponds to an id within a server node. No `RANK`. So the W&B should be initialised only if `NODE_RANK=0` and `LOCAL_NODE=0`.

From PTL docs on the distributed data-parallel scheme:
![image](https://github.com/datamol-io/graphium/assets/102740547/7873eafd-aa29-4dde-b2d3-e90ffca0edad)

**Comment by maciej-sypetkowski** [comment]
That's a weird way to start a multigpu job. Use `torchrun` and it should be fine.

**Comment by blazejba** [comment]
This "weird way" is how PyTorch Lightning handles multi-GPU execution when `devices` is set to >1.
https://pytorch-lightning.readthedocs.io/en/0.9.0/multi_gpu.html

Might be worth either mentioning in the documentation to use `torchrun`, or changing the env vars as instructed above, because then multi-gpu would work also when starting the script with `python`.

**Comment by DomInvivo** [comment]
Why not use the `graphium-train` command in the `README.md`? Doesn't that one work with `devices > 1`?

**Comment by DomInvivo** [comment]
Closing since `torchrun` fixes the issue. But we can keep discussing
