### ISSUE TITLE
Torchmetrics error: AttributeError: 'Tensor' object has no attribute 'clear'

### ISSUE THREAD

**Issue by AnujaSomthankar** [datamol-io/graphium#524]
### Error Description

Branch: `Torchmetrics`

While training LargeMix, run fails early on (during sanity) in `metrics.py` when it calls the reset function (line 407) with the error `AttributeError: 'Tensor' object has no attribute 'clear'. Did you mean: 'char'?`

Commenting `# strategy: ddp_find_unused_parameters_true` in the configuration yaml file overcomes this error. 
In the metrics configuration, it specifically fails for task PCBA's AVPR metrics. It also fails for PCBA's AUROC metric when its `multitask-handling` is set to `mean-per-label`.

**Comment by DomInvivo** [comment]
Branch `torchmetrics` was fixed and merged in PR #511
